function [ fenv ] = pdFilterEnvelope( k, j, filterObject )
%PDFILTERENVELOPE Apply filter and build envelope
    
    fenv = computeEnvelope(...
        applyFilterToData( ...
        channelData( k, j, 'TimeSeries' ),...
        channelData( k, j, 'Fs', 'NoValidation', true ),...
        filterObject )...
        );
    
end

