 
m{1} = {'MLAT','fclmMLAT',{}};
m{2} = {'Array','fclmArray',...
        {...
        {'xliml','Lower boundry X axis','localization:array:xliml'},...
        {'xlimh','Higher boundry X axis','localization:array:xlimh'},...
        {'xres','Resolution on X axis','localization:array:xres'},...
        {'yliml','Lower boundry Y axis','localization:array:yliml'},...
        {'ylimh','Higher boundry Y axis','localization:array:ylimh'},...
        {'yres','Resolution on Y axis','localization:array:yres'},...
        {'zliml','Lower boundry Z axis','localization:array:zliml'},...
        {'zlimh','Higher boundry Z axis','localization:array:zlimh'},...
        {'zres','Resolution on Z axis','localization:array:zres'},...
        }};
