
control.mg = [];
control.mg.k = 0;
control.mg.channelsFilter = [];
control.mg.nAxes = 1; % this value is for startup, dont change!
control.mg.axesHeight = getParam('mainGUI:axesHeight');
control.mg.tm.startVerticalLines = [];
control.mg.tm.endVerticalLines = [];
control.mg.so.startVerticalLines = [];
control.mg.so.endVerticalLines = [];
control.mg.su.startVerticalLines = [];
control.mg.su.endVerticalLines = [];
control.mg.Mpwpd.startVerticalLines = [];
control.mg.Mpwpd.endVerticalLines = [];
control.mg.Rm.on = false;
control.mg.Rm.startVerticalLines = [];
control.mg.Rm.endVerticalLines = [];
control.mg.Rm.startVerticalLines = [];
control.mg.Rm.endVerticalLines = [];
control.mg.callsMarks = [];
control.mg.callsNumbers = [];
control.mg.linkAxes = false;
